export type CyberMapSettings = {
  theme: string;
  background: string;
  language: string;
  aiProvider: string;
  aiModel: string;
  aiBaseUrl: string;
  thinkingMode: string;
  aiTemperature: string;
  aiMaxTokens: string;
  aiPrivacyMode: string;
  aiApiKeyConfigured: boolean;
  agentPreset: string;
  agentIntegrationType: string;
  agentCommand: string;
  agentWorkingDirectory: string;
  agentTimeoutSeconds: string;
  agentRequiresApproval: boolean;
  agentSandboxEnabled: boolean;
  agentNetworkAccess: boolean;
  mcpTransport: string;
  connectorPreset: string;
  requireHumanApproval: boolean;
  sandboxEnabled: boolean;
  auditLogsEnabled: boolean;
};
